mybatis:
  mapper-locations: classpath:mapper/*DaoMapper.xml
  type-aliases-package: com.cloud.user.entity
server:
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    include: data
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates
      suffix: .html
  thymeleaf:
    cache: false